Algoritmo "semnome"
// Disciplina   : [Algoritmos e Programação (TIC 24.1)]
// Professor   : Fabrício Herpich 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 13/06/2024
Var
// Seção de Declarações das variáveis 
valores : vetor[1..10][1..10] de inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 


Fimalgoritmo