Algoritmo "semnome"
// Disciplina   : [Algoritmos e Programação]
// Professor   : Fabrício Herpich 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 13/04/2024
Var
// Seção de Declarações das variáveis 
i , n : inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval ("Digite um número maior que zero: ")
leia (n)

para i de 0 ate n passo 1 faca
escreval(i*2)
fimpara

Fimalgoritmo