Algoritmo "semnome"
// Disciplina   : [Algoritmos e Programação]
// Professor   : Fabrício Herpich
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 13/04/2024
Var
// Seção de Declarações das variáveis
n, soma : inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
soma <- 0
n <- 0

repita
soma <- soma + n
escreval(soma)
escreval ("Digite um número: ")
leia (n)
ate (n < 0)


Fimalgoritmo